## Web scraping Qiyas National Center for Assessment website, for schools ranking based on average students grades in both exams Qudrat and Tahseli.

- https://www.qiyas.sa

In [3]:
# impor required libraries:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [200]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup
from time import sleep
from selenium import webdriver

In [201]:


def scraping_scores(test, sex, spec, pages = None):

    df = pd.DataFrame(columns=['الترتيب العام',
                 'الرقم الوزاري',
                 'اسم المدرسة',
                 'المدينة',
                 'المنطقة',
                 'نوع المدرسة',
                 'التصنيف',
                 'المتوسط',
                'نوع الاختبار',
                'الجنس',
                'المسار'])

    driver = webdriver.Chrome(executable_path='./chromedriver/chromedriver')
    # request the url data
    driver.get('https://www.qiyas.sa/ar/Statistics-Data/Schools/Pages/DetResults.aspx')
    
    elem_1 = driver.find_element_by_id(test)
    elem_1.click()
    
    elem_2 = driver.find_element_by_id(sex)
    elem_2.click()
        
    elem_3 = driver.find_element_by_id(spec)
    elem_3.click()

    show = driver.find_element_by_id("ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_btnSubmit")
    show.click()

    HTML = driver.page_source
    soup = BeautifulSoup(HTML, "html.parser")

    TEST = soup.find("label", {"for": test}).text
    SEX = soup.find("label", {"for": sex}).text
    SPEC = soup.find("label", {"for": spec}).text

    sleep(2)
    status = True
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    sleep(2)
    page = 1
    while status: 
        # sleep 3 second (wait)
        sleep(2)
        #driver.implicitly_wait(2)
        # catch data
        driver.implicitly_wait(8) # seconds

        HTML = driver.page_source
        soup = BeautifulSoup(HTML, "html.parser")
        table = soup.find("div", {"class": "row photoalbumList"})
        rows = table.find_all("tr")

        for row in rows[2:] :
              df.loc[len(df)] = [x.text.strip() for x in row.find_all("td")] + [TEST, SEX, SPEC]
        
        if pages == page:
            break

        try:
            elem = driver.find_element_by_class_name('Next')
            elem.click()
            page +=1
        except:
            sleep(1)
        try:
            soup.find("a", {"class", "aspNetDisabled Next"}).text
            status = False
        except:
            pass
    driver.close()  
    return df
#close the data
# driver.close()

In [203]:
# This dataframe (df1) includes  Qudrat Theoretical (humanity exam) path for Boys.
df1 = scraping_scores('ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_rbCapabilities','ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbBoy','ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbTheoretical',21)

In [28]:

Girl_T_Sci = pd.DataFrame(columns=['الترتيب العام',
                 'الرقم الوزاري',
                 'اسم المدرسة',
                 'المدينة',
                 'المنطقة',
                 'نوع المدرسة',
                 'التصنيف',
                 'المتوسط',
                'نوع الاختبار',
                'الجنس',
                'المسار'])

driver = webdriver.Chrome(executable_path='./chromedriver/chromedriver')
# request the url data
driver.get('https://www.qiyas.sa/ar/Statistics-Data/Schools/Pages/DetResults.aspx')
for test in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_rbAchievement']:
    elem_1 = driver.find_element_by_id(test)
    elem_1.click()
    for sex in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbGirl']:
        elem_2 = driver.find_element_by_id(sex)
        elem_2.click()
        for spec in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbScientific']:
            
            
            elem_3 = driver.find_element_by_id(spec)
            elem_3.click()
            
            show = driver.find_element_by_id("ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_btnSubmit")
            show.click()
            
            HTML = driver.page_source
            soup = BeautifulSoup(HTML, "html.parser")
            
            TEST = soup.find("label", {"for": test}).text
            SEX = soup.find("label", {"for": sex}).text
            SPEC = soup.find("label", {"for": spec}).text

            sleep(2)
            status = True
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            sleep(2)
            while status: 
                # sleep 3 second (wait)
                sleep(2)
                #driver.implicitly_wait(2)
                # catch data
                #driver.implicitly_wait(8) # seconds

                HTML = driver.page_source
                soup = BeautifulSoup(HTML, "html.parser")
                table = soup.find("div", {"class": "row photoalbumList"})
                rows = table.find_all("tr")
                
                for row in rows[2:] :
                    Girl_T_Sci.loc[len(Girl_T_Sci)] = [x.text.strip() for x in row.find_all("td")] + [TEST, SEX, SPEC]
                try:
                    elem = driver.find_element_by_class_name('Next')
                    elem.click()
                except:
                    sleep(1)
                
                try:
                    soup.find("a", {"class", "aspNetDisabled Next"}).text
                    status = False
                except:
                    pass
#close the data
# driver.close()

In [29]:
Girl_T_Sci.shape

(1861, 11)

In [32]:
# open the web browser
Girl_T_Theor = pd.DataFrame(columns=['الترتيب العام',
                 'الرقم الوزاري',
                 'اسم المدرسة',
                 'المدينة',
                 'المنطقة',
                 'نوع المدرسة',
                 'التصنيف',
                 'المتوسط',
                'نوع الاختبار',
                'الجنس',
                'المسار'])

driver = webdriver.Chrome(executable_path='./chromedriver/chromedriver')
# request the url data
driver.get('https://www.qiyas.sa/ar/Statistics-Data/Schools/Pages/DetResults.aspx')
for test in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_rbAchievement']:
    elem_1 = driver.find_element_by_id(test)
    elem_1.click()
    for sex in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbGirl']:
        elem_2 = driver.find_element_by_id(sex)
        elem_2.click()
        for spec in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbTheoretical']:
            
            
            elem_3 = driver.find_element_by_id(spec)
            elem_3.click()
            
            show = driver.find_element_by_id("ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_btnSubmit")
            show.click()
            
            HTML = driver.page_source
            soup = BeautifulSoup(HTML, "html.parser")
            
            TEST = soup.find("label", {"for": test}).text
            SEX = soup.find("label", {"for": sex}).text
            SPEC = soup.find("label", {"for": spec}).text

            sleep(2)
            status = True
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            sleep(2)
            while status: 
                # sleep 3 second (wait)
                sleep(2)
                #driver.implicitly_wait(2)
                # catch data
                driver.implicitly_wait(8) # seconds

                HTML = driver.page_source
                soup = BeautifulSoup(HTML, "html.parser")
                table = soup.find("div", {"class": "row photoalbumList"})
                rows = table.find_all("tr")
                
                for row in rows[2:] :
                    Girl_T_Theor.loc[len(Girl_T_Theor)] = [x.text.strip() for x in row.find_all("td")] + [TEST, SEX, SPEC]
                try:
                    elem = driver.find_element_by_class_name('Next')
                    elem.click()
                except:
                    sleep(1)
                
                try:
                    soup.find("a", {"class", "aspNetDisabled Next"}).text
                    status = False
                except:
                    pass
#close the data
# driver.close()

In [34]:
Girl_T_Theor.shape

(1644, 11)

In [27]:
# open the web browser
Boy_T_sci = pd.DataFrame(columns=['الترتيب العام',
                 'الرقم الوزاري',
                 'اسم المدرسة',
                 'المدينة',
                 'المنطقة',
                 'نوع المدرسة',
                 'التصنيف',
                 'المتوسط',
                'نوع الاختبار',
                'الجنس',
                'المسار'])

driver = webdriver.Chrome(executable_path='./chromedriver/chromedriver')
# request the url data
driver.get('https://www.qiyas.sa/ar/Statistics-Data/Schools/Pages/DetResults.aspx')
for test in['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_rbAchievement']:
    elem_1 = driver.find_element_by_id(test)
    elem_1.click()
    for sex in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbBoy']:
        elem_2 = driver.find_element_by_id(sex)
        elem_2.click()
        for spec in ['ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_RbScientific']:
           
            elem_3 = driver.find_element_by_id(spec)
            elem_3.click()
            
            show = driver.find_element_by_id("ctl00_ctl37_g_70814aa2_183d_441e_9095_82a1744d5849_ctl00_btnSubmit")
            show.click()
            
            HTML = driver.page_source
            soup = BeautifulSoup(HTML, "html.parser")
            
            TEST = soup.find("label", {"for": test}).text
            SEX = soup.find("label", {"for": sex}).text
            SPEC = soup.find("label", {"for": spec}).text

            sleep(2)
            status = True
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            sleep(2)
            while status: 
                # sleep 3 second (wait)
                sleep(2)
                #driver.implicitly_wait(2)
                # catch data
                #driver.implicitly_wait(8) # seconds

                HTML = driver.page_source
                soup = BeautifulSoup(HTML, "html.parser")
                table = soup.find("div", {"class": "row photoalbumList"})
                rows = table.find_all("tr")
                
                for row in rows[2:] :
                    Boy_T_sci.loc[len(Boy_T_sci)] = [x.text.strip() for x in row.find_all("td")] + [TEST, SEX, SPEC]
                try:
                    elem = driver.find_element_by_class_name('Next')
                    elem.click()
                except:
                    pass
                   # sleep(1)
                
                try:
                    soup.find("a", {"class", "aspNetDisabled Next"}).text
                    status = False
                except:
                    pass
#close the data
# driver.close()

In [41]:
Boy_T_sci.shape

(10, 11)

# Saving and viewing the scraped data:

In [459]:
# This dataframe (df) includes Science Track for:
# Boys (Taseli and Qudrat), AND Girls(Tahseli and Qudrat)
df.to_csv('Schools_Exams_scores.csv')

In [4]:
#extra step to show scraped dataframe content
df= pd.read_csv('Schools_Exams_scores.csv')

In [5]:
df.head(5)

,Unnamed: 0,الترتيب العام,الرقم الوزاري,اسم المدرسة,المدينة,المنطقة,نوع المدرسة,التصنيف,المتوسط,نوع الاختبار,الجنس,المسار
0,0,1.0,153038.0,مدارس البسام العالمية الثانوية,الدمام,الشرقية,تعليم أجنبي,تعليم أجنبي بنين,89.27,قدرات,بنين,علمي
1,1,2.0,325145.0,الفيصلية الثانوية,جدة,مكة المكرمة,حكومي,مقررات,87.37,قدرات,بنين,علمي
2,2,3.0,454730.0,ثانوية الرواد,الجبيل,الشرقية,حكومي,مقررات,87.04,قدرات,بنين,علمي
3,3,4.0,11175.0,ثانوية منارات الرياض الأهلية,الرياض,الرياض,أهلي,مقررات,86.07,قدرات,بنين,علمي
4,4,5.0,53854.0,ثانوية الجامعة الأهلية,الخبر,الشرقية,أهلي,تعليم عام بنين,85.47,قدرات,بنين,علمي

In [205]:
# This dataframe (df1) includes  Qudrat Theoretical (humanity exam) path for Boys.
df1.to_csv('Qudrat_Boys_Theor.csv')

In [6]:
#extra step to show scraped dataframe content
df1=pd.read_csv('Qudrat_Boys_Theor.csv')

In [7]:
df1.head(5)

,Unnamed: 0,الترتيب العام,الرقم الوزاري,اسم المدرسة,المدينة,المنطقة,نوع المدرسة,التصنيف,المتوسط,نوع الاختبار,الجنس,المسار
0,0,1.0,11555.0,ثانوية الإمام ابن كثير المكي لتحفيظ القرآن الكريم,الرياض,الرياض,حكومي,تحفيظ بنين,82.19,قدرات,بنين,نظري
1,1,2.0,40493.0,ثانوية الإمام عاصم بن أبي النجود لتحفيظ القران...,المدينة المنورة,المدينة المنورة,حكومي,تحفيظ بنين,81.05,قدرات,بنين,نظري
2,2,3.0,11706.0,ثانوية مجمع صالح الراجحي لتحفيظ القرآن الكريم,الرياض,الرياض,حكومي,تحفيظ بنين,80.88,قدرات,بنين,نظري
3,3,4.0,200271.0,المعهد العلمي في محافظة الدرعيـة - المرحلة الث...,الدرعية,الرياض,معهد جامعة الامام,NaN,80.54,قدرات,بنين,نظري
4,4,5.0,10857.0,ثانوية أبي عمرو البصري لتحفيظ القرآن الكريم,الرياض,الرياض,حكومي,تحفيظ بنين,80.02,قدرات,بنين,نظري

In [39]:
# This dataframe (Girl_T_Theor) includes  Thaseli Theoretical (humanity exam) path for Girls.
Girl_T_Theor.to_csv('Girl_Tahseli_Theoretical.csv')

In [8]:
Girl_T_Theor=pd.read_csv('Girl_Tahseli_Theoretical.csv')
Girl_T_Theor.head(5)

,Unnamed: 0,الترتيب العام,الرقم الوزاري,اسم المدرسة,المدينة,المنطقة,نوع المدرسة,التصنيف,المتوسط,نوع الاختبار,الجنس,المسار
0,0,1,58830,ثانوية تحفيظ القرآن الأولى بالهفوف.,الأحساء,الشرقية,حكومي,تحفيظ بنات,83.86,تحصيلي,بنات,نظري
1,1,2,55554,الثانوية الثانية لتحفيظ القرآن بالدمام,الدمام,الشرقية,حكومي,تحفيظ بنات,80.42,تحصيلي,بنات,نظري
2,2,3,59198,ثانوية حفصة بنت عمر لتحفيظ القرآن الكريم.,الأحساء,الشرقية,حكومي,تحفيظ بنات,80.22,تحصيلي,بنات,نظري
3,3,4,55512,الثانوية الأولى لتحفيظ القرآن بالدمام,الدمام,الشرقية,حكومي,تحفيظ بنات,79.64,تحصيلي,بنات,نظري
4,4,5,16670,الثانوية الأولى لتحفيظ القرآن الكريم بالدلم,الدلم,الرياض,حكومي,تحفيظ بنات,79.35,تحصيلي,بنات,نظري

In [38]:
Girl_T_Sci.to_csv('Girl_Tahseli_Science.csv')

In [9]:
Girl_T_Sci=pd.read_csv('Girl_Tahseli_Science.csv')
Girl_T_Sci.head(5)

,Unnamed: 0,الترتيب العام,الرقم الوزاري,اسم المدرسة,المدينة,المنطقة,نوع المدرسة,التصنيف,المتوسط,نوع الاختبار,الجنس,المسار
0,0,1,55915,ثانوية مدارس الظهران الاهلية (مقررات),الخبر,الشرقية,أهلي,مقررات,92.00,تحصيلي,بنات,علمي
1,1,2,55919,ثانوية مدارس الجامعة الاهلية للبنات,الخبر,الشرقية,أهلي,تعليم عام بنات,87.51,تحصيلي,بنات,علمي
2,2,3,422495,مدارس منارات المدينة المنورة الأهلية - المرحلة...,المدينة المنورة,المدينة المنورة,أهلي,مقررات,87.46,تحصيلي,بنات,علمي
3,3,4,155010,مدارس السلام الخاصة للبنات - نظام المقررات,الخبر,الشرقية,أهلي,مقررات,87.24,تحصيلي,بنات,علمي
4,4,5,55921,ثانوية مدارس العزيزيه الاهلية للبنات,الخبر,الشرقية,أهلي,تعليم عام بنات,86.72,تحصيلي,بنات,علمي